"""addd INTERVIEW_TYPEs

Revision ID: 363cbf853f73
Revises: d7ef92bca7eb
Create Date: 2025-09-28 13:25:22.548060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '363cbf853f73'
down_revision = 'd7ef92bca7eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('duration', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('interviewer_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('date',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('interviewer_name')
        batch_op.drop_column('duration')
        batch_op.drop_column('notes')
        batch_op.drop_column('location')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
