"""addd INTERVIEW_TYPE

Revision ID: d7ef92bca7eb
Revises: 3de65f5350ce
Create Date: 2025-09-28 12:57:14.183241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7ef92bca7eb'
down_revision = '3de65f5350ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interview_type', sa.String(length=150), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.drop_column('interview_type')

    # ### end Alembic commands ###
